### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by andrecarlucci** [daltskin/CustomVision-TensorFlow-CSharp#3]
Have you tried with a new model exported lately?
When using a model exported last year, it works just fine. I tried today with a new model and it doesn't work anymore.
Any ideas?

I'm getting an exception:
```
Exception thrown: 'TensorFlow.TFException' in TensorFlowSharp.dll
An exception of type 'TensorFlow.TFException' occurred in TensorFlowSharp.dll but was not handled in user code
Input to reshape is a tensor with 97556 values, but the requested shape requires a multiple of 90944
	 [[Node: block0_0_reshape0 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](block0_0_concat, block0_0_reshape0/shape)]]
```

**Comment by DiegoVil** [comment]
i tried 4 february working fine ( classification)

**Comment by daltskin** [comment]
I've created a wip branch that should work for both multi label & multi class models.  

Here: https://github.com/daltskin/CustomVision-TensorFlow-CSharp/tree/multiclass_multilabel

**Comment by daltskin** [comment]
There was also a change in May 2018 where mean values are now 0,0,0 - so I've updated the code for that also: https://docs.microsoft.com/en-us/azure/cognitive-services/custom-vision-service/release-notes
